version: '1'
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
