services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
